AWSTemplateFormatVersion: "2010-09-09"
Description: "Hello Cluster"
Resources:
    helloVpc:
      Type: "AWS::EC2::VPC"
      Properties:
        CidrBlock: "10.0.0.0/16"

    helloSubnetA:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId: !Ref helloVpc
        CidrBlock: "10.0.0.0/24"

    helloSubnetB:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId: !Ref helloVpc
        CidrBlock: "10.0.1.0/24"a

    helloClusterRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: helloClusterRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "eks.amazonaws.com"
              Action: "sts:AssumeRole"
    helloCluster:
      Type: "AWS::EKS::Cluster"
      Properties:
        Name: helloCluster
        Version: "1.14"
        RoleArn: !Ref helloClusterRole
        ResourcesVpcConfig:
          SecurityGroupIds:
            - !GetAtt helloVpc.DefaultSecurityGroup
          SubnetIds:
            - !Ref helloSubnetA
            - !Ref helloSubnetB


